apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.1.5
      # tag: 2023.10.5@sha256:3b2810093b118a77c87f3639e51930ffb0f10e8af679ba8582843e9bbfdd5fa5

    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16.1@sha256:dda75857689116d9c233ec0978cb905da0f952618dfbe1b8731aa1071044eaf0
        env:
          - name: INIT_POSTGRES_HOST
            value: postgres.database.svc.cluster.local
          - name: INIT_POSTGRES_SUPER_USER
            value: postgres
          - name: INIT_POSTGRES_SUPER_PASS
            value: ${POSTGRES_SUPER_PASS}
          - name: INIT_POSTGRES_USER
            value: postgres
          - name: INIT_POSTGRES_PASS
            value: ${POSTGRES_SUPER_PASS}
          - name: INIT_POSTGRES_DBNAME
            value: *app
      install-hacs:
        image: busybox:1.36.1@sha256:6d9ac9237a84afe1516540f40a0fafdc86859b2141954b4d643af7066d598b74
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            # renovate: github-release depName=hacs/integration
            HACS_VERSION="1.33.0"
            mkdir -p /config/custom_components
            rm -rf /config/custom_components/hacs
            busybox wget -qO- "https://github.com/hacs/integration/releases/download/$${HACS_VERSION}/hacs.zip"  | busybox unzip -d /config/custom_components/hacs -
        volumeMounts:
          - name: config
            mountPath: /config
      copy-config:
        image: busybox:latest@sha256:6d9ac9237a84afe1516540f40a0fafdc86859b2141954b4d643af7066d598b74
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /configfiles/* /config/
        volumeMounts:
          - name: config
            mountPath: /config
          - name: configfiles
            mountPath: /configfiles

    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"
    dnsConfig:
      options:
        - name: ndots
          value: "1"

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # cert-manager.io/cluster-issuer: letsencrypt
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/name: Home Assistant
          # gethomepage.dev/description: Open source home automation
          # gethomepage.dev/group: Applications
          # gethomepage.dev/icon: home-assistant.png
        hosts:
          - host: &hass-host "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *hass-host

    # podAnnotations:
    #   configmap.reloader.stakater.com/reload: home-assistant-config

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
      configfiles:
        enabled: true
        type: configMap
        name: home-assistant-config

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn        