apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:QBKv/yMJvx146Foh4N+1NNwAFXKAV187+ApRx0aYFcUvBIrt,iv:AQOSgxzV5zbcr0IdfYn+A5JdT8qaJrgPQQ74nFawf6g=,tag:wHVeQpzD0GiPSu/zi4LqMw==,type:str]
    credentials.json: ENC[AES256_GCM,data:AXRnb/vPPUASf8qxnV4s1xLhfXtQIJxHoA1DZ19BQT7Gf7g7B9igaeShq/c713t34lISIOZ3wG8hkYRWNsvdOs1gGnqqQQbFVs7LnBBVGY3ofyCXL8XJMDsvh1Qq2ZpMoXvqggLc/qQwFKHOmduPqEoS6lqsreYLM+u92kUZjHdbDpWq/LVx60NXMymVs3ODVzdxvvgn9JSeFrFqth5t3UQrmmHxoR6Pl7WIhnevPA==,iv:gx2VnouAzDsxDem2yEgizp4tToHf/cBd6oFJxedLxpM=,tag:ljmyJHFaJi4O/xzB+aKKUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc3RndWhtQTJOVlowRFlo
            aVdHWTJGWkFFZlJXbGRGQUhqSld0b1ljdzFBCjBoOVdkanRCZi84emZ4a3Rwanoy
            UThDREZLL2x5aWMyVnRwZmo5S3JzOEUKLS0tIG1RK2tiSVVCcjVuTXVoUmd5KzJ4
            NUozOVdjQ2lBeWJIWncwdDE2aExpOVEKv47nI/663jr8nd4vWzNxijRQXb191ots
            7PO6mWVlNvtroS1aRSlQeDcR/K1xDR7DkC0N5YdonVpxFCV4t+OkvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T08:46:52Z"
    mac: ENC[AES256_GCM,data:B3rT8PRM8u7Af57iw4/inne+6NSTL2GWp61FphcMVg0ANeF8I0ZpHx5lQ9EErC5ph9FsCQuIV1KzYTdo+x2Esu9o/8xNfi/2wsoBmLOHCBrL1N8L1nnl3GbF8fTnCnNOP+Nu+80HhsJkJeW8L31oP/uBh2kjFUEqt5OJkx5g/yg=,iv:r3ZZLl5jzpMpOFzEMncgorxRcTt4tFQaUes61ziHydw=,tag:uVKmxd4WUIbbzzSXQaBkvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
