apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:yrolNUF55XUX8kwgKFovuLjAxgHju5PP,iv:h7wR11sPc90pns7Gm5c0FRSFDDSJ/VLWnSRD4XvjBFA=,tag:djY69FJPwOMRSgPV0vDnDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Wk43OWNtb1NkUWh2a0p0
            b1FxbktMRzVwU0htVTJDMGNYTnJhaFVqMWdZCmhYUHhnWTBQZ3Bqbm9NenZWSjFr
            YmNaZWNpZk9aT055WU1EMnhvUTdoblkKLS0tIGRxMW1nb204bVRnVWdSeWdZM3Y4
            Y282SGRHMHlsaEplZThndVZyWDFJSWsK1Tmtanx5XOFwu0HjHheNLw+XVrDBPWU0
            Vav4RssP9Ox2oroNKnE1VO39dW7T2w8pmkoTNwqq54tw57/m+srdtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T15:59:37Z"
    mac: ENC[AES256_GCM,data:NuX43ObNk6dIXB2YGKG1wlC74ZXV1VkEX+zkkZYiNYuHI5MvBeBmpQYnu1eMdWLiHjZlrwBMOImJw1dasHpNJZmxj6GOTtiO87yPHJaGv/35ZXg6J/hK05zZZQJ64jhGqopfT5ZCXvT6Hnr+ZxB0LN7Eaz+lgZ4loroaOk/Zvm4=,iv:1sB8x+h2t8yZbAjdOlTTOeWwie50CDKTiKs4fAsD4s4=,tag:HWOq34Fi14lf5/R78yDXjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
