---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-kube
provisioner: nfs.csi.k8s.io
parameters:
  server: truenas
  share: /mnt/lab-pool/k3s-nfs/config-pvc
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
