---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mariadb
spec:
  interval: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 15.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    primary:
      extraEnvVars:
      - name: TZ
        value: "${TIMEZONE}"
      persistence:
        enabled: true
        existingClaim: mariadb-nfs 
        storageClassName: nfs-kube
      readinessProbe:
        initialDelaySeconds: 35
        periodSeconds: 5
        failureThreshold: 10
      livenessProbe:
        initialDelaySeconds: 35
        periodSeconds: 5
        failureThreshold: 10
    image:
      debug: true
    auth:
      rootPassword: "${MARIADB_ROOT_PASSWORD}"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 512Mi
    initdbScripts:
      create-photoprism.sql: |
        CREATE DATABASE IF NOT EXISTS photoprism
        CHARACTER SET = 'utf8mb4'
        COLLATE = 'utf8mb4_unicode_ci';

        CREATE USER IF NOT EXISTS 'photoprism'@'%' IDENTIFIED BY '${PHOTOPRISM_DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON photoprism.* to 'photoprism'@'%';

      create-monica.sql: |
        CREATE DATABASE IF NOT EXISTS monica
        CHARACTER SET = 'utf8mb4'
        COLLATE = 'utf8mb4_unicode_ci';

        CREATE USER IF NOT EXISTS 'monica'@'%' IDENTIFIED BY '${MONICA_DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON monica.* to 'monica'@'%';
      
      create-ghost.sql: |
        CREATE DATABASE IF NOT EXISTS ghost
        CHARACTER SET = 'utf8mb4'
        COLLATE = 'utf8mb4_unicode_ci';

        CREATE USER IF NOT EXISTS 'ghost'@'%' IDENTIFIED BY '${GHOST_DB_PASSWORD}';
        GRANT ALL PRIVILEGES ON ghost.* to 'ghost'@'%';
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-nfs
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-kube
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.32.1.5"
    path: /mnt/lab-pool/k3s-nfs/config-pvc
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-kube
  resources:
    requests:
      storage: 2Gi