apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:a4mLWKYXhKp+nZsCQ3dSPe5qubNGYRxl5LHK5vDjLGdYHJU=,iv:dURPGyxhO8hqozt66exCpAkezyKQnDeJu/nxRP7UaB0=,tag:vxKNcPzwP+yQfgptHibKHw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wYKoZef4jHjKzJJmWjpuKTMTcbqtgqt/VjYKQzrMoYFt5JkO,iv:XlCv0Vd8l2xQiqIV4qsNe+IEXwClkPKlWzqoFtiVY4c=,tag:tHWe3I0FrB2zDM+Pl+uzOw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/6FFz2KUUZDHwZiKtZ+bmQ==,iv:Dyg+P5FJIrQkm1E/hBGNvSvXmC3018Egcv84TcuryBk=,tag:1jj2IjeCmtkTxBxW3qEMrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb09uYmxwejY0cXprVSs3
            SDMxMUdtc0h2bmdCTGtVZWhHbm53MFEvTndJCnBlVm9hQTBZZEQxOVJ0OFl2Ni9Z
            T1RUaXdtUHBvTzlrYkFOT1MwOGRiTWcKLS0tIG1XZXV2Z1JsaW5CcUhDRzdsa1lT
            dEdnQWczZ2ZueTd1a2RPRUVsOGNrWmcKhTz1x03R1hK9rhJQGbq+QcBJ4dyEEcya
            Amx2Z3NIk+8GY9WJRst4lu3CsJmxOx89gUjxHn22S4ohdeox+1xvZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T15:59:32Z"
    mac: ENC[AES256_GCM,data:d63wg8JrDzVUUFqCxRKZZTHP2Cx+Ds6aqSOwl8IjNIUB3yJDNNnIBiwMBMW/2Atf8Sd6TSYISI4jCxB6Uhksw23+BaAt/nbqL6mLZWPoKvJGvzRAqdgQ8OWg/qmiPNZJV5ElbH+lStR8oLzt8TZGwla7UjIoexqedDILm8suX2c=,iv:ZzZzBMZjndovuT/Oiws/ZExGMkqfLrXo+PnvHVsyKo8=,tag:hj8aSRjq71TuMZFf+tuOYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
