apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:mY1x/EEydJog5aPd,iv:zxT90drcz9snikxlHd/QjM/kTt9IJuHEwV6PUY2rWYo=,tag:jsbXAEiLQk5E2KTYYzCHeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WEhTQ0hVbmR5YktUdVli
            OEZGQ29JcFhENjV0TDVqYjFVeGdiQ2d6RzFZClNPMnFXb3Y0dDVkVUVFM3puTVpx
            cHdZRDAvOXhNeGliM3ZyeElGODNzazAKLS0tIHNJcEt5S09yYXh2bnZOdGlTMWxV
            bDU1ZW5ocG9sVG1WVVk2U0ZCMU50TG8KGzmdWOWqgfs+u5FN1stTtAR/v0eL8onC
            D3oOzFWQtbhmRKMkw2KG2YNiJyE4gAH3UkT89r4cHU0tm/4eXvlNHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-24T08:46:41Z"
    mac: ENC[AES256_GCM,data:tFeO4jtlVoglI+17bvxCVYLD2HEKfHb1W7+Vkms5o8ixqyhn+oenM8HLRfIIs6AphOWPZsiBeeIACUzlKCaSjyyOiq9aG3t6RIdJA1LECmK2Dtu9AnxF7V+eVb+ZuzRRKgtyvdWK7zm0ZDH76EjkxeBWmPOA3IoL8Fgld2TjyAE=,iv:YxOq3zQYi6FYq1D3EGenDx6aCR4DDUqyOFigbH3jRtk=,tag:bUiZSdc1NjrIxuMQYmGf5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
