---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    defaultSettings:
      backupTarget: "nfs://10.32.1.5:/mnt/lab-pool/backup/longhorn"
      defaultReplicaCount: 3
    longhornUI:
      replicas: 3
    ingress:
      enabled: true
      ingressClassName: "internal"
      host: longhorn.${SECRET_DOMAIN}
      path: /
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
