---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ghost
spec:
  dependsOn:
    - name: ghost-mariadb-01
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    image:
      repository: ghost
      tag: 5.38@sha256:0ba58c36c53813933023cca728a026f1f9f1b129364350021fdf6703ae148829
    env:
      TZ: "${TIMEZONE}"
      url: "https://uitm.${SECRET_DOMAIN}"
      database__client: mysql
      database__connection__host: ghost-mariadb-01.media.svc.cluster.local
      database__connection__user: ${SECRET_GHOST_MARIADB_USER}
      database__connection__password: ${SECRET_GHOST_MARIADB_PASS}
      database__connection__database: ${SECRET_GHOST_MARIADB_DB}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "post"
          # external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "uitm.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      content:
        enabled: true
        existingClaim: ghost-v1
    mariadb:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost-mariadb-01
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    auth:
      # database__connection__host: ghost-mariadb
      rootPassword: ${MEDIA_GHOST_DB_ROOT_PASSWORD}
      username: ${SECRET_GHOST_MARIADB_USER}
      password: ${SECRET_GHOST_MARIADB_PASS}
      database: ${SECRET_GHOST_MARIADB_DB}
    persistence:
      existingClaim: ghost-db-pvc-v1     
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db-pvc-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi  
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghost
              # renovate: datasource=docker depName=ghost
              tag: "5.75.3"
            env:
              TZ: "${TIMEZONE}"
              url: "https://uitm.${SECRET_DOMAIN}"
              admin__url: "https://ghost.${SECRET_DOMAIN}"
              database__client: mysql
              database__connection__host: ghost-mariadb-01.media.svc.cluster.local
              database__connection__database: ghost
              database__connection__user: ghost
              database__connection__password: ${SECRET_GHOST_MARIADB_PASS}
              mail__transport: SMTP
              mail__from: ${MAIILGUN_FROM_EMAIL}
              mail__options__service: Mailgun
              mail__options__host: smtp.eu.mailgun.org
              mail__options__port: 587
              mail__options__secure: true
              mail__options__auth__user: postmaster@${SECRET_DOMAIN}
              mail__options__auth__pass: ${MAILGUN_SMTP_PASSWORD}
            resources:
              requests:
                cpu: 15m
                memory: 256M
              limits:
                memory: 1Gi
    service:
      main:
        ports:
          http:
            port: 2368
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host "${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      admin:
        enabled: true
        className: nginx
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      content:
        enabled: true
        existingClaim: ghost-config-v1