---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ghost-01
spec:
  dependsOn:
    - name: ghost-mariadb-01
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  interval: 15m
  maxHistory: 2
  timeout: 20m
  install:
    remediation:
      retries: 300
  upgrade:
    remediation:
      retries: 300
  values:
    image:
      repository: ghost
      tag: 5.76@sha256:c18d718e6ec98d358a7b5dba684841a430689e3202ae614359ee47334fb06f59
    env:
      TZ: "${TIMEZONE}"
      url: "https://uitm.${SECRET_DOMAIN}"
      database__client: mysql
      database__connection__host: ghost-mariadb-01.media.svc.cluster.local
      database__connection__user: ${SECRET_GHOST_MARIADB_USER}
      database__connection__password: ${SECRET_GHOST_MARIADB_PASS}
      database__connection__database: ${SECRET_GHOST_MARIADB_DB}
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "post"
          # external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "uitm.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      content:
        enabled: true
        existingClaim: ghost-v1
    mariadb:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ghost-mariadb-01
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    auth:
      # database__connection__host: ghost-mariadb-01
      rootPassword: ${SECRET_GHOST_MARIADB_PASS}
      username: ${SECRET_GHOST_MARIADB_USER}
      password: ${SECRET_GHOST_MARIADB_PASS}
      database: ${SECRET_GHOST_MARIADB_DB}
    persistence:
      existingClaim: ghost-db-pvc-v1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db-pvc-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi  