apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:TergfCncQgv6NCEBZpR/dua/91YMGUASbJ0RA7SxSeC+SkAsmC9LTg==,iv:gyavDHZPZRq7SQ4kjIDWgF7Q0cfkJuZVuvq20p/GriU=,tag:RRYANJRBDK+1I1sFnAlKQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ncefsf8cvx4qchq4v5vvnzrvsk0wt4qjn462t6st8p5yz8etlapqyert6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U0d0NHM0bXdOd2ltQ241
            YnVsWkFPOHY1djh2VHdNeklWNVZiT0ZuNGhVCmYyTzQvN2dpeW43SUpPQ2ppK2hT
            MDJqVFBXeXRrbDlCSGo3N3p3L0g0L0kKLS0tIHM0RVpKT1VES01RT2QxOGg4V0M4
            Zlg5dERyTExqazhFclEzSnVLMkhjOEEKaP8wcE4KNXuffiTgAlyOF9p3H80rkjey
            w1pKTMbWYojx+giRdl8/nzV22jzhLKGJABa3G1RSA6Tk78rsICbUbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T15:06:43Z"
    mac: ENC[AES256_GCM,data:ZXTHJLGRiERrLivLptuDtNAv6Oa+FQnS8NwUA3kiZMUhza5duJtU8PyhGRE1Mm4e8icyKq0n4qr/URlKFMf7C2JEZSPZuGzzyRwa0GTwRlM5VoKFu5y3pTn9dL+0ECIMKmc+8teivVIQjj9nlcd0UfI3dxIAi5DFNEGEdRlcgdg=,iv:cGeLetLUaWFnCA/r6f5NxsR3tKLeLS/O86WUC+YNM+I=,tag:fhhjvt/yGmXCBgZvh1D8Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
